# This workflow builds a Cordova Android app using GitHub Actions
# Place this file at .github/workflows/cordova-android.yml

name: Build Cordova Android App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Cordova CLI
        run: npm install -g cordova

      - name: Install Java (for Android build)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # - name: Install Android SDK
      #   uses: android-actions/setup-android@v3

      - name: Install project dependencies
        run: npm install || echo "No npm dependencies"

      - name: Add Android platform
        run: cordova platform add android@latest

      - name: Add required plugins
        run: |
          cordova plugin add cordova-plugin-camera-preview@0.13.0
          cordova plugin add cordova-plugin-device
          cordova plugin add cordova-plugin-android-permissions
          cordova plugin add cordova-plugin-media

      - name: Build Android APK
        run: cordova build android 

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: platforms/android/app/build/outputs/apk/debug/*.apk
